name: Selenium Allure Reports

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: 'maven'

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Install Allure CLI
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure-version: '2.32.0'

      - name: Run Selenium Tests (Headless)
        run: |
          export CHROME_BIN=$(which google-chrome)
          export CHROMEDRIVER_BIN=$(which chromedriver)
          xvfb-run -a mvn clean test \
            -Dallure.results.directory=target/allure-results \
            -Dselenium.browser=chrome-headless
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          allure generate target/allure-results -o target/allure-report --clean

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report
          path: target/allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/allure-report
          publish_branch: gh-pages
          force_orphan: true
